# Generated by Django 3.2.13 on 2022-05-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=10)),
                ('Password', models.CharField(max_length=8)),
                ('isactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=20)),
                ('selling_price', models.IntegerField(default=' ')),
                ('discount_price', models.IntegerField(default='')),
                ('description', models.TextField()),
                ('brand', models.CharField(default='', max_length=10)),
                ('category', models.CharField(choices=[('M', 'MEN'), ('F', 'FEMALE'), ('K', 'KIDS')], max_length=2)),
                ('subcategory', models.CharField(choices=[('MS', 'Men-Shoes'), ('MT', 'Men-Tops'), ('MB', 'Men-Bottom'), ('CC', 'Men-Casual'), ('G', 'Men-gym'), ('WS', 'Women-Shoes'), ('WT', 'Women-Tops'), ('WB', 'Women-Bottom'), ('KT', 'kids_t-shirt'), ('KG', 'kids-gear'), ('KW', 'kids-watch'), ('KS', 'kids-shoes')], max_length=50)),
                ('shoes_img', models.ImageField(upload_to='media_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=25)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Mobile', models.IntegerField(default=0)),
                ('City', models.CharField(default='', max_length=10)),
                ('State', models.CharField(default='', max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='order_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default='1')),
                ('delivery_charges', models.IntegerField(default=80)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On_The_Way', 'On_The_Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.master')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.master'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default='1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.master')),
            ],
        ),
    ]
