# Generated by Django 3.2.13 on 2022-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0002_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
