# Generated by Django 3.2.13 on 2022-05-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0003_alter_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
