# Generated by Django 3.2.13 on 2022-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0004_auto_20220513_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.PositiveSmallIntegerField(default=' '),
        ),
    ]
