# Generated by Django 3.2.13 on 2022-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
