# Generated by Django 3.2.13 on 2022-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0009_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_count',
            field=models.IntegerField(default=0),
        ),
    ]
