# Generated by Django 3.2.13 on 2022-05-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0010_cart_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_count',
        ),
    ]
