# Generated by Django 3.2.13 on 2022-05-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0012_cart_cart_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.master'),
            preserve_default=False,
        ),
    ]
