# Generated by Django 3.2.13 on 2022-05-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0013_product_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Master',
        ),
        migrations.AddField(
            model_name='product',
            name='Profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='e_commerce_App.profile'),
            preserve_default=False,
        ),
    ]
