# Generated by Django 3.2.13 on 2022-05-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0014_auto_20220518_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Profile',
        ),
    ]
