# Generated by Django 3.2.13 on 2022-05-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_App', '0015_remove_product_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_place',
            name='delivery_charges',
        ),
    ]
